//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsistenciaAClase
    {
        public int IDASISTENCIA { get; set; }
        public int IDCLIENTE { get; set; }
        public int IDCLASE { get; set; }
        public Nullable<System.DateTime> FECHAASISTENCIA { get; set; }
    
        public virtual Clase Clase { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
