//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clase()
        {
            this.AsistenciaAClase = new HashSet<AsistenciaAClase>();
        }
    
        public int IDCLASE { get; set; }
        public string NOMBRECLASE { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<System.TimeSpan> HORARIO { get; set; }
        public int HABILITADO { get; set; }
        public Nullable<int> IDTurno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsistenciaAClase> AsistenciaAClase { get; set; }
        public virtual Turno Turno { get; set; }
    }
}
