//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.AsistenciaAClase = new HashSet<AsistenciaAClase>();
            this.Opinion = new HashSet<Opinion>();
        }
    
        public int IDCLIENTE { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public string TIPODEPLAN { get; set; }
        public Nullable<int> IdTipoUsuario { get; set; }
        public Nullable<int> IDTIPOCONTRATO { get; set; }
        public Nullable<int> IDSEXO { get; set; }
        public Nullable<int> HABILITADO { get; set; }
        public Nullable<int> TIENEUSUARIO { get; set; }
        public string TIPOUSUARIO { get; set; }
        public Nullable<int> IDPLAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsistenciaAClase> AsistenciaAClase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinion { get; set; }
        public virtual PlanMembresia PlanMembresia { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
