//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoGimnasio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int IDOPINION { get; set; }
        public int IDCLIENTE { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<int> PUNTUACION { get; set; }
        public Nullable<System.DateTime> FECHAOPINION { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
